name: Abbey Grant Kit Generate Policy Input

on:
  pull_request:
jobs:
  output-plan:
    runs-on: ubuntu-latest
    env:
      TF_VAR_abbey_token: ${{ secrets.ABBEY_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        id: setup
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Terraform Init
        id: init
        run: terraform init
        env:
          TF_HTTP_USERNAME: quickstart
          TF_HTTP_PASSWORD: ${{ secrets.ABBEY_TOKEN }}

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false -out=tfplan
        env:
          TF_HTTP_USERNAME: quickstart
          TF_HTTP_PASSWORD: ${{ secrets.ABBEY_TOKEN }}
